In [ ]:
###------------------   question of list     ---------------------------------------------

In [2]:
#1. Write a Python program which accepts a sequence of comma-separated numbers 
#from user and generate a list and a tuple with those numbers.

num1=input("Enter the number sequence: ")
list=num1.split(",")
tuple=tuple(list)
print("List is: ",list)
print("tuple is: ",tuple)


Enter the number sequence: 3,5,7,13
List is:  ['3', '5', '7', '13']
tuple is:  ('3', '5', '7', '13')


In [7]:
# 2. Write a Python program to display the first and last colors from the following list.
# color_list = ["Red","Green","White" ,"Black"]

color=["Red","Green","White","Black"]
first_color=color[0]
last_color=color[-1]
print(first_color)
print(last_color)

Red
Black


In [14]:
# 3. Write a Python program to print the even numbers from a given list.
#  Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]

list1=[1, 2, 3, 4, 5, 6, 7, 8, 9]
list2=[i for i in list1 if i % 2 == 0]

print(list1)
print("list1 even is: ",list2)


[1, 2, 3, 4, 5, 6, 7, 8, 9]
list1 even is:  [2, 4, 6, 8]


In [ ]:
##---------------------------------   Module      --------------------------------------------------------

In [3]:
## 1. Write a Python program to calculate number of days between two dates. Hint: use Datetime package/module.

from datetime import datetime

date1=datetime(2014,7,2)
date2=datetime(2014,7,11)
date_diff=date2 - date1
print(date_diff.days," days")

9  days


In [6]:
d1=input("Enter the First date(yyyy,mm,dd): ")
d2=input("Enter the second date(yyyy,mm,dd): ")
d1_int=datetime.strptime(d1,"%Y-%m-%d")
d2_int=datetime.strptime(d2,"%Y-%m-%d")
d_diff=d2_int-d1_int
print(d_diff.days," days")

Enter the First date(yyyy,mm,dd): 2014-07-02
Enter the First date(yyyy,mm,dd): 2014-07-11
9  days


In [25]:
##-------------------------------------   Function    ----------------------------------------------------

In [26]:
## 1. Write a Python program to get the volume of a sphere with radius 6.

import math

In [28]:
radius=6
volume=(4/3) * math.pi * radius**3
print("Volume of sphere: ",volume)

Volume of sphere:  904.7786842338603


In [35]:
## 2. Write a Python program to calculate the sum of three given numbers,
#if the values are equal then return three times of their sum hint:write User defined functions

a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
c=int(input("Enter the thrid number: "))

def three_number(a,b,c):
    if a==b==c:
        return (a+b+c)*3
    else:
        return a+b+c

print(three_number(a,b,c))

Enter the first number: 1
Enter the second number: 2
Enter the thrid number: 3
6


In [39]:
## 3.  Write a Python program to count the number 4 in a given list.
##  List = [1,4,6,8,4,9,4]

from scipy import stats

list_count=[1,4,6,8,4,9,4]

stats.mode(list_count)

C:\Users\sohel\AppData\Local\Temp\ipykernel_15616\1047034756.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(list_count)


ModeResult(mode=array([4]), count=array([3]))

In [8]:
list=[1,4,6,8,4,9,4]
count=0
for i in list:
    if i == 4:
        count=count+1
print(count)


3


In [12]:
## 4. Write a Python program to print all even numbers from a given numbers list in the same order 
# and stop the printing if any numbers that come after 237 in the sequence. Go to the editorSample numbers list :

# 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
# 815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
# 958,743, 527]

num_list=[399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
958,743, 527]
empty_list=[]
for i in num_list:
    if i % 2 ==0:
        empty_list.append(i)
    elif i == 237:
        break
print(empty_list)

[162, 758, 918]


In [44]:
## 5. Write a Python program to find those numbers 
## which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included)

for i in range(1500,2701):
    if i % 7 == 0 and i % 5 == 0:
        print(i)

1505
1540
1575
1610
1645
1680
1715
1750
1785
1820
1855
1890
1925
1960
1995
2030
2065
2100
2135
2170
2205
2240
2275
2310
2345
2380
2415
2450
2485
2520
2555
2590
2625
2660
2695


In [51]:
## 6. Write a Python program that prints all the numbers from 0 to 6 except 3 and 6.
##  Note : Use 'continue' statement.

for i in range(0,7):
    if i == 3 or i == 6:
        continue
    print(i)


0
1
2
4
5


In [ ]:
## 7. Write a Python program to get the Fibonacci series between 0 to 50.
# Note : The Fibonacci Sequence is the series of numbers :
# 0, 1, 1, 2, 3, 5, 8, 13, 21, ....
# Every next number is found by adding up the two numbers before it.


In [58]:
## 9. Write a Python function that takes a list and returns a new list with unique elements of the first list.
# Sample List : [1,2,3,3,3,3,4,5]

import numpy as np

list_unique=[1,2,3,3,3,3,4,5]
new_list=np.array(list_unique)
unq_list=np.unique(new_list)
print("unique element list: ",unq_list)



unique element list:  [1 2 3 4 5]


In [15]:
list_1=[1,2,3,3,3,3,4,5]
empty_list1=[]

for i in list_1:
    if i not in empty_list1:
        empty_list1.append(i)      
print(empty_list1)

[1, 2, 3, 4, 5]


In [17]:
##-----------------------------------------       Dictionary            ----------------------------------------------

##1. Write a Python script to concatenate following dictionaries to create a new one.

##dic1={1:10, 2:20},      dic2={3:30, 4:40},             dic3={5:50,6:60}

dis1={1:10, 2:20}
dis2={3:30, 4:40}
dis3={5:50, 6:60}
empty_dis={}

empty_dis.update(dis1)
empty_dis.update(dis2)
empty_dis.update(dis3)

print(empty_dis)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


In [36]:
##---------------------------------------      Series      ------------------------------------------------------


## 1. Write a Python program to add, subtract, multiple and divide two Pandas Series.
##  Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

import pandas as pd

series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

addition = series1 + series2
print("Addition:")
print(addition)


subtraction= series1 - series2
print("Subtraction:")
print(subtraction)


multiplication = series1 * series2
print("Multipliction:")
print(multiplication)



division =  series1 / series2
print("Division")
print(division)


Addition:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multipliction:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Division
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [ ]:
##----------------------------------------       Basic Programs      -----------------------------------------------

In [ ]:
## 1. Write Python Programs to use various operators in Python

In [45]:
## 1. Arithmetic Operators:

a = 13
b = 6

## " '+' - addition" operator use for adding two number
addition = a+b         
print("addition of two number: ",addition)

## " '-' subtraction " operator use for subtracting two number / find the difference between two number
subtraction = a-b
print("subtraction of two number: ",subtraction)

## " '*' -multiplication / product" operator use for multipluing / product of the two number
multiplying = a*b
print("multiplication of two number: ",multiplying)

## " '/' - divisio" operator use for divide the two number
divide = a/b
print("division of two number: ",divide)

## " '//' - result only" operator give only result of division not remander
result= a//b
print("result of division: ",result)

## " '%'' - module" operator give only remainder of division
module= a/b
print("module of division: ",module)

## " '**' - Exponentiation / power"
power= a**b
print("Exponentiation: ",power)

addition of two number:  19
subtraction of two number:  7
multiplication of two number:  78
division of two number:  2.1666666666666665
result of division:  2
module of division:  2.1666666666666665
Exponentiation:  4826809


In [47]:
## 2. Comparison Operators:

x = 8
y = 10

## " '>' - Greater than"
grater_than = x>y
print("grater than: ",grater_than)

## " '<' - Less than"
less_than = x<y
print("less than: ",less_than)

## " '==' - Equal to"
equal = x==y
print("equal to: ",equal)

## " '!=' - Not equal to"
not_equal = x!=y
print("not equal: ",not_equal)

## " '>=' - Greater than equal"
GTE = x >= y
print("greater than equal: ",GTE)

## " '<=' - Less than equal"
LTE = x<=y
print("less than equal: ",LTE)




grater than:  False
less than:  True
equal to:  False
not equal:  True
greater than equal:  False
less than equal:  True


In [61]:
## 3. Logical Operators:

x = 6

## "'And' Operator" Returns True if both statements are true
logical_And = x>3 and x<8
print("logical and: ",logical_And)

logical1_and = x>4 and x>8
print("logical and: ",logical1_and)

## " 'or' Operator" Returns True if one of the statements is true or if both the statement is false than returns false
logical_Or = x>7 or x<9
print("logical or: ",logical_Or)

logical1_or = x>7 or x<6
print("logical1 or: ",logical1_or)

## " 'not' Operator" Reverse the result, returns False if the result is true
logical_Not = not(x>3 and x<8)
print("logical not: ",logical_Not)

logical1_Not =  not(x>7 or x<6)
print("logical not: ",logical1_Not)


logical and:  True
logical and:  False
logical or:  True
logical1 or:  False
logical not:  False
logical not:  True


In [74]:
## 2. Create list of elements and slice and dice it

elements=["bue","balck","green","red",4,7,89,98]

list_slice1=elements[2:7]
print("Print the list using index range: ",list_slice1)

list_slice2=elements[:3:2]
print("Print the list using index range and step: ",list_slice2)

list_slice3=elements[::-1]
print("Print the list in reversed order: ",list_slice3)

elements[3:7]=["orange",100]
print("Print the replace value from the list: ",elements)

Print the list using index range:  ['green', 'red', 4, 7, 89]
Print the list using index range and step:  ['bue', 'green']
Print the list in reversed order:  [98, 89, 7, 4, 'red', 'green', 'balck', 'bue']
Print the replace value from the list:  ['bue', 'balck', 'green', 'orange', 100, 98]


In [78]:
## 3. Using while loop accept numbers until sum of numbers is less than 100

sum = 0
while sum<100:
    num = int(input("Enter the number: "))
    sum = num+1
print("sum ont exceed 100")

Enter the number: 99
sum ont exceed 100


In [17]:
sum = 0

for i in range(1,200):
    num=int(input("Enter the number: "))
    sum =i + num
    if sum>=100:
         break
print("Sum not exceed 100")

Enter the number: 1
Enter the number: 2
Enter the number: 99
Sum not exceed 100


In [24]:
## 6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy

import numpy as np

matrix = np.arange(2,11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [27]:
## 7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

num_list= [1,3,4,5,6,7]
array_list=np.array(num_list)
print("Numpy array: ",array_list)

Numpy array:  [1 3 4 5 6 7]


In [37]:
## 8. "Write a Python program to create a null vector of size 10 and update sixth value to 11.

vector=np.zeros(10)
print(vector)
vector[6]=11
print("Update valuea: ",vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update valuea:  [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
## 4. Write a python program Read & write Excel files 

In [ ]:
## 5. Write a python program to scrape reviews from a commercial web site

In [ ]:
##--------------------------------------      Data Frame     -----------------------------------------------

In [ ]:
## 1.  Write a Pandas program to select the specified columns and rows from a given data frame. 
##Go to the editorSample Python dictionary data and list labels:

In [39]:
## 2. Use Crime dataset from LMS

import pandas as pd

df = pd.read_csv(r"C:\Users\sohel\Desktop\Excelr Assignment\Python Assignment\crime_data.csv")